general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"


[window]
opacity = 0.98
decorations = "Transparent"
padding.x = 8 
padding.y = 25
dynamic_padding = true

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
size = 14

[cursor]
style.shape = "Underline"
style.blinking = "On"

